data = {
    "AAL": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "AAL",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Attribution Assurance Licenses",
        "url": "https://opensource.org/licenses/AAL"
    },
    "AFL-3.0": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "AFL-3.0",
        "maintainer": "Lawrence Rosen",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Academic Free License 3.0",
        "url": "https://opensource.org/licenses/AFL-3.0"
    },
    "AGPL-3.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "AGPL-3.0",
        "legacy_ids": [
            "agpl-v3"
        ],
        "maintainer": "Free Software Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "GNU Affero General Public License v3",
        "url": "https://opensource.org/licenses/AGPL-3.0"
    },
    "APL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "APL-1.0",
        "legacy_ids": [
            "apl1.0"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Adaptive Public License 1.0",
        "url": "https://opensource.org/licenses/APL-1.0"
    },
    "APSL-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "APSL-2.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Apple Public Source License 2.0",
        "url": "https://opensource.org/licenses/APSL-2.0"
    },
    "Against-DRM": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "Against-DRM",
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Against DRM",
        "url": "https://opendefinition.org/licenses/against-drm"
    },
    "Apache-1.1": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Apache-1.1",
        "maintainer": "Apache Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "retired",
        "title": "Apache Software License 1.1",
        "url": "https://opensource.org/licenses/Apache-1.1"
    },
    "Apache-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Apache-2.0",
        "legacy_ids": [
            "apache2.0"
        ],
        "maintainer": "Apache Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Apache Software License 2.0",
        "url": "https://opensource.org/licenses/Apache-2.0"
    },
    "Artistic-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Artistic-2.0",
        "legacy_ids": [
            "artistic-license-2.0"
        ],
        "maintainer": "Perl Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Artistic License 2.0",
        "url": "https://opensource.org/licenses/Artistic-2.0"
    },
    "BSD-2-Clause": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "BSD-2-Clause",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "BSD 2-Clause \"Simplified\" or \"FreeBSD\" License (BSD-2-Clause)",
        "url": "https://opensource.org/licenses/BSD-2-Clause"
    },
    "BSD-3-Clause": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "BSD-3-Clause",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "BSD 3-Clause \"New\" or \"Revised\" License (BSD-3-Clause)",
        "url": "https://opensource.org/licenses/BSD-3-Clause"
    },
    "BSL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "BSL-1.0",
        "legacy_ids": [
            "bsl1.0"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Boost Software License 1.0",
        "url": "https://opensource.org/licenses/BSL-1.0"
    },
    "BitTorrent-1.1": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "BitTorrent-1.1",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "BitTorrent Open Source License 1.1",
        "url": "https://spdx.org/licenses/BitTorrent-1.1"
    },
    "CATOSL-1.1": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "CATOSL-1.1",
        "legacy_ids": [
            "ca-tosl1.1"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Computer Associates Trusted Open Source License 1.1 (CATOSL-1.1)",
        "url": "https://opensource.org/licenses/CATOSL-1.1"
    },
    "CC-BY-4.0": {
        "domain_content": True,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "CC-BY-4.0",
        "maintainer": "Creative Commons",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Creative Commons Attribution 4.0",
        "url": "https://creativecommons.org/licenses/by/4.0/"
    },
    "CC-BY-NC-4.0": {
        "domain_content": True,
        "domain_data": True,
        "domain_software": False,
        "family": "Creative Commons",
        "id": "CC-BY-NC-4.0",
        "maintainer": "Creative Commons",
        "od_conformance": "rejected",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Creative Commons Attribution-NonCommercial 4.0",
        "url": "https://creativecommons.org/licenses/by-nc/4.0/"
    },
    "CC-BY-SA-4.0": {
        "domain_content": True,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "CC-BY-SA-4.0",
        "maintainer": "Creative Commons",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Creative Commons Attribution Share-Alike 4.0",
        "url": "https://creativecommons.org/licenses/by-sa/4.0/"
    },
    "CC0-1.0": {
        "domain_content": True,
        "domain_data": True,
        "domain_software": True,
        "family": "",
        "id": "CC0-1.0",
        "maintainer": "Creative Commons",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "CC0 1.0",
        "url": "https://creativecommons.org/publicdomain/zero/1.0/"
    },
    "CDDL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "CDDL-1.0",
        "legacy_ids": [
            "cddl1"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Common Development and Distribution License 1.0",
        "url": "https://opensource.org/licenses/CDDL-1.0"
    },
    "CECILL-2.1": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "CECILL-2.1",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "CeCILL License 2.1",
        "url": "https://opensource.org/licenses/CECILL-2.1"
    },
    "CNRI-Python": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "CNRI-Python",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "CNRI Python License",
        "url": "https://opensource.org/licenses/CNRI-Python"
    },
    "CPAL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "CPAL-1.0",
        "legacy_ids": [
            "cpal_1.0"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Common Public Attribution License 1.0",
        "url": "https://opensource.org/licenses/CPAL-1.0"
    },
    "CUA-OPL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "CUA-OPL-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "CUA Office Public License 1.0",
        "url": "https://opensource.org/licenses/CUA-OPL-1.0"
    },
    "DSL": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "DSL",
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Design Science License",
        "url": "https://opendefinition.org/licenses/dsl"
    },
    "ECL-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "ECL-2.0",
        "legacy_ids": [
            "ecl2"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Educational Community License 2.0",
        "url": "https://opensource.org/licenses/ECL-2.0"
    },
    "EFL-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "EFL-2.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Eiffel Forum License 2.0",
        "url": "https://opensource.org/licenses/EFL-2.0"
    },
    "EPL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "EPL-1.0",
        "legacy_ids": [
            "eclipse-1.0"
        ],
        "maintainer": "Eclipse Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "retired",
        "title": "Eclipse Public License 1.0",
        "url": "https://opensource.org/licenses/EPL-1.0"
    },
    "EPL-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "EPL-2.0",
        "legacy_ids": [
            "eclipse-2.0"
        ],
        "maintainer": "Eclipse Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Eclipse Public License 2.0",
        "url": "https://opensource.org/licenses/EPL-2.0"
    },
    "EUDatagrid": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "EUDatagrid",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "EU DataGrid Software License",
        "url": "https://opensource.org/licenses/EUDatagrid"
    },
    "EUPL-1.1": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "EUPL-1.1",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "European Union Public License 1.1",
        "url": "https://opensource.org/licenses/EUPL-1.1"
    },
    "Entessa": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Entessa",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Entessa Public License",
        "url": "https://opensource.org/licenses/Entessa"
    },
    "FAL-1.3": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "FAL-1.3",
        "maintainer": "Copyleft Attitude",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Free Art License 1.3",
        "url": "https://opendefinition.org/licenses/fal"
    },
    "Fair": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Fair",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Fair License",
        "url": "https://opensource.org/licenses/Fair"
    },
    "Frameworx-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Frameworx-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Frameworx License 1.0",
        "url": "https://opensource.org/licenses/Frameworx-1.0"
    },
    "GFDL-1.3-no-cover-texts-no-invariant-sections": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "GFDL-1.3-no-cover-texts-no-invariant-sections",
        "maintainer": "Free Software Foundation",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "GNU Free Documentation License 1.3 with no cover texts and no invariant sections",
        "url": "https://opendefinition.org/licenses/gfdl"
    },
    "GPL-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "GPL-2.0",
        "maintainer": "Free Software Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "GNU General Public License 2.0",
        "url": "https://opensource.org/licenses/GPL-2.0"
    },
    "GPL-3.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "GPL-3.0",
        "maintainer": "Free Software Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "GNU General Public License 3.0",
        "url": "https://opensource.org/licenses/GPL-3.0"
    },
    "HPND": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "HPND",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Historical Permission Notice and Disclaimer",
        "url": "https://opensource.org/licenses/HPND"
    },
    "IPA": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "IPA",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "IPA Font License",
        "url": "https://opensource.org/licenses/IPA"
    },
    "IPL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "IPL-1.0",
        "legacy_ids": [
            "ibmpl"
        ],
        "maintainer": "IBM Corporation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "IBM Public License 1.0",
        "url": "https://opensource.org/licenses/IPL-1.0"
    },
    "ISC": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "ISC",
        "legacy_ids": [
            "isc-license"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "ISC License",
        "url": "https://opensource.org/licenses/ISC"
    },
    "Intel": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Intel",
        "legacy_ids": [
            "intel-osl"
        ],
        "maintainer": "Intel Corporation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "retired",
        "title": "Intel Open Source License",
        "url": "https://opensource.org/licenses/Intel"
    },
    "LGPL-2.1": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "LGPL-2.1",
        "maintainer": "Free Software Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "GNU Lesser General Public License 2.1",
        "url": "https://opensource.org/licenses/LGPL-2.1"
    },
    "LGPL-3.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "LGPL-3.0",
        "maintainer": "Free Software Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "GNU Lesser General Public License 3.0",
        "url": "https://opensource.org/licenses/LGPL-3.0"
    },
    "LO-FR-2.0": {
        "domain_content": False,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "LO-FR-2.0",
        "is_generic": False,
        "maintainer": "Etalab",
        "od_conformance": "not reviewed",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Open License 2.0",
        "url": "https://www.etalab.gouv.fr/licence-ouverte-open-licence"
    },
    "LPL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "LPL-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "retired",
        "title": "Lucent Public License (\"Plan9\") 1.0",
        "url": "https://opensource.org/licenses/LPL-1.0"
    },
    "LPL-1.02": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "LPL-1.02",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Lucent Public License 1.02",
        "url": "https://opensource.org/licenses/LPL-1.02"
    },
    "LPPL-1.3c": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "LPPL-1.3c",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "LaTeX Project Public License 1.3c",
        "url": "https://opensource.org/licenses/LPPL-1.3c"
    },
    "MIT": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "MIT",
        "legacy_ids": [
            "mit-license"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "MIT License",
        "url": "https://opensource.org/licenses/MIT"
    },
    "MPL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "MPL-1.0",
        "maintainer": "Mozilla Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "retired",
        "title": "Mozilla Public License 1.0",
        "url": "https://opensource.org/licenses/MPL-1.0"
    },
    "MPL-1.1": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "MPL-1.1",
        "legacy_ids": [
            "mozilla1.1"
        ],
        "maintainer": "Mozilla Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "retired",
        "title": "Mozilla Public License 1.1",
        "url": "https://opensource.org/licenses/MPL-1.1"
    },
    "MPL-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "MPL-2.0",
        "legacy_ids": [
            "mozilla2.0"
        ],
        "maintainer": "Mozilla Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Mozilla Public License 2.0",
        "url": "https://opensource.org/licenses/MPL-2.0"
    },
    "MS-PL": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "MS-PL",
        "maintainer": "Microsoft Corporation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Microsoft Public License",
        "url": "https://opensource.org/licenses/MS-PL"
    },
    "MS-RL": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "MS-RL",
        "maintainer": "Microsoft Corporation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Microsoft Reciprocal License",
        "url": "https://opensource.org/licenses/MS-RL"
    },
    "MirOS": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "MirOS",
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "approved",
        "status": "active",
        "title": "MirOS Licence",
        "url": "https://opensource.org/licenses/MirOS"
    },
    "Motosoto": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Motosoto",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Motosoto License",
        "url": "https://opensource.org/licenses/Motosoto"
    },
    "Multics": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Multics",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Multics License",
        "url": "https://opensource.org/licenses/Multics"
    },
    "NASA-1.3": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "NASA-1.3",
        "legacy_ids": [
            "nasa1.3"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "NASA Open Source Agreement 1.3",
        "url": "https://opensource.org/licenses/NASA-1.3"
    },
    "NCSA": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "NCSA",
        "legacy_ids": [
            "uoi-ncsa"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "University of Illinois/NCSA Open Source License",
        "url": "https://opensource.org/licenses/NCSA"
    },
    "NGPL": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "NGPL",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Nethack General Public License",
        "url": "https://opensource.org/licenses/NGPL"
    },
    "NPOSL-3.0": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "NPOSL-3.0",
        "legacy_ids": [
            "nosl3.0"
        ],
        "maintainer": "Lawrence Rosen",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Non-Profit Open Software License 3.0",
        "url": "https://opensource.org/licenses/NPOSL-3.0"
    },
    "NTP": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "NTP",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "NTP License",
        "url": "https://opensource.org/licenses/NTP"
    },
    "Naumen": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Naumen",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Naumen Public License",
        "url": "https://opensource.org/licenses/Naumen"
    },
    "Nokia": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Nokia",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Nokia Open Source License",
        "url": "https://opensource.org/licenses/Nokia"
    },
    "OCLC-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "OCLC-2.0",
        "legacy_ids": [
            "oclc2"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "OCLC Research Public License 2.0",
        "url": "https://opensource.org/licenses/OCLC-2.0"
    },
    "ODC-BY-1.0": {
        "domain_content": False,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "ODC-BY-1.0",
        "maintainer": "Open Data Commons",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Open Data Commons Attribution License 1.0",
        "url": "https://opendefinition.org/licenses/odc-by"
    },
    "ODbL-1.0": {
        "domain_content": False,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "ODbL-1.0",
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Open Data Commons Open Database License 1.0",
        "url": "https://opendefinition.org/licenses/odc-odbl"
    },
    "OFL-1.1": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "OFL-1.1",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Open Font License 1.1",
        "url": "https://opensource.org/licenses/OFL-1.1"
    },
    "OGL-Canada-2.0": {
        "domain_content": True,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "OGL-Canada-2.0",
        "is_generic": False,
        "legacy_ids": [
            "OGL-CA-2.0"
        ],
        "maintainer": "Government of Canada",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Open Government License 2.0 (Canada)",
        "url": "https://open.canada.ca/en/open-government-licence-canada"
    },
    "OGL-UK-1.0": {
        "domain_content": True,
        "domain_data": True,
        "domain_software": True,
        "family": "",
        "id": "OGL-UK-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "not reviewed",
        "status": "superseded",
        "title": "Open Government Licence 1.0 (United Kingdom)",
        "url": "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/"
    },
    "OGL-UK-2.0": {
        "domain_content": True,
        "domain_data": True,
        "domain_software": True,
        "family": "",
        "id": "OGL-UK-2.0",
        "is_generic": False,
        "maintainer": "UK Government",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Open Government Licence 2.0 (United Kingdom)",
        "url": "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
    },
    "OGL-UK-3.0": {
        "domain_content": True,
        "domain_data": True,
        "domain_software": True,
        "family": "",
        "id": "OGL-UK-3.0",
        "is_generic": False,
        "maintainer": "UK Government",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Open Government Licence 3.0 (United Kingdom)",
        "url": "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
    },
    "OGTSL": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "OGTSL",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Open Group Test Suite License",
        "url": "https://opensource.org/licenses/OGTSL"
    },
    "OSL-3.0": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "OSL-3.0",
        "maintainer": "Lawrence Rosen",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Open Software License 3.0",
        "url": "https://opensource.org/licenses/OSL-3.0"
    },
    "PDDL-1.0": {
        "domain_content": False,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "PDDL-1.0",
        "legacy_ids": [
            "ODC-PDDL-1.0"
        ],
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Open Data Commons Public Domain Dedication and Licence 1.0",
        "url": "https://opendefinition.org/licenses/odc-pddl"
    },
    "PHP-3.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "PHP-3.0",
        "maintainer": "PHP Group",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "PHP License 3.0",
        "url": "https://opensource.org/licenses/PHP-3.0"
    },
    "PostgreSQL": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "PostgreSQL",
        "maintainer": "PostgreSQL Global Development Group",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "PostgreSQL License",
        "url": "https://opensource.org/licenses/PostgreSQL"
    },
    "Python-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Python-2.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Python License 2.0",
        "url": "https://opensource.org/licenses/Python-2.0"
    },
    "QPL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "QPL-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Q Public License 1.0",
        "url": "https://opensource.org/licenses/QPL-1.0"
    },
    "RPL-1.5": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "RPL-1.5",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Reciprocal Public License 1.5",
        "url": "https://opensource.org/licenses/RPL-1.5"
    },
    "RPSL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "RPSL-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "RealNetworks Public Source License 1.0",
        "url": "https://opensource.org/licenses/RPSL-1.0"
    },
    "RSCPL": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "RSCPL",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Ricoh Source Code Public License",
        "url": "https://opensource.org/licenses/RSCPL"
    },
    "SISSL": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "SISSL",
        "legacy_ids": [
            "sun-issl"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "retired",
        "title": "Sun Industry Standards Source License 1.1",
        "url": "https://opensource.org/licenses/SISSL"
    },
    "SPL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "SPL-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Sun Public License 1.0",
        "url": "https://opensource.org/licenses/SPL-1.0"
    },
    "SimPL-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "SimPL-2.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Simple Public License 2.0",
        "url": "https://opensource.org/licenses/SimPL-2.0"
    },
    "Sleepycat": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Sleepycat",
        "maintainer": "Oracle Corporation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Sleepycat License",
        "url": "https://opensource.org/licenses/Sleepycat"
    },
    "Talis": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "Talis",
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Talis Community License",
        "url": "https://opendefinition.org/licenses/tcl"
    },
    "Unlicense": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Unlicense",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Unlicense",
        "url": "https://unlicense.org/"
    },
    "VSL-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "VSL-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Vovida Software License 1.0",
        "url": "https://opensource.org/licenses/VSL-1.0"
    },
    "W3C": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "W3C",
        "maintainer": "World Wide Web Consortium",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "W3C License",
        "url": "https://opensource.org/licenses/W3C"
    },
    "WXwindows": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "WXwindows",
        "maintainer": "wxWidgets Team",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "wxWindows Library License",
        "url": "https://opensource.org/licenses/WXwindows"
    },
    "Watcom-1.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Watcom-1.0",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Sybase Open Watcom Public License 1.0",
        "url": "https://opensource.org/licenses/Watcom-1.0"
    },
    "Xnet": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Xnet",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "X.Net License",
        "url": "https://opensource.org/licenses/Xnet"
    },
    "ZPL-2.0": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "ZPL-2.0",
        "maintainer": "Zope Foundation",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "Zope Public License 2.0",
        "url": "https://opensource.org/licenses/ZPL-2.0"
    },
    "Zlib": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "Zlib",
        "legacy_ids": [
            "zlib-license"
        ],
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "zlib/libpng license",
        "url": "https://opensource.org/licenses/Zlib"
    },
    "dli-model-use": {
        "domain_content": False,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "dli-model-use",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "not reviewed",
        "status": "retired",
        "title": "Statistics Canada: Data Liberation Initiative (DLI) - Model Data Use Licence",
        "url": "http://data.library.ubc.ca/datalib/geographic/DMTI/license.html"
    },
    "geogratis": {
        "domain_content": False,
        "domain_data": True,
        "domain_software": False,
        "family": "",
        "id": "geogratis",
        "maintainer": "",
        "od_conformance": "",
        "osd_conformance": "not reviewed",
        "status": "retired",
        "title": "Geogratis",
        "url": "http://geogratis.gc.ca/geogratis/licenceGG"
    },
    "hesa-withrights": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "hesa-withrights",
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Higher Education Statistics Agency Copyright with data.gov.uk rights",
        "url": "https://web.archive.org/web/20131009082944/http://www.hesa.ac.uk/index.php?option=com_content&task=view&id=2619&Itemid=209"
    },
    "localauth-withrights": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "localauth-withrights",
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Local Authority Copyright with data.gov.uk rights",
        "url": ""
    },
    "met-office-cp": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "met-office-cp",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Met Office UK Climate Projections Licence Agreement",
        "url": "https://www.metoffice.gov.uk/climatechange/science/monitoring/ukcp09/UKCIP08_license_agreement_130709.pdf"
    },
    "mitre": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": True,
        "family": "",
        "id": "mitre",
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "approved",
        "status": "active",
        "title": "MITRE Collaborative Virtual Workspace License (CVW License)",
        "url": "https://opensource.org/licenses/CVW"
    },
    "other-at": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "other-at",
        "is_generic": True,
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Other (Attribution)",
        "url": ""
    },
    "other-nc": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "other-nc",
        "is_generic": True,
        "maintainer": "",
        "od_conformance": "not reviewed",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Other (Non-Commercial)",
        "url": ""
    },
    "other-open": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "other-open",
        "is_generic": True,
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Other (Open)",
        "url": ""
    },
    "other-pd": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "other-pd",
        "is_generic": True,
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "Other (Public Domain)",
        "url": ""
    },
    "ukclickusepsi": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "ukclickusepsi",
        "maintainer": "",
        "od_conformance": "rejected",
        "osd_conformance": "not reviewed",
        "status": "retired",
        "title": "UK Click Use PSI",
        "url": ""
    },
    "ukcrown": {
        "domain_content": False,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "ukcrown",
        "maintainer": "",
        "od_conformance": "rejected",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "UK Crown Copyright",
        "url": ""
    },
    "ukcrown-withrights": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "ukcrown-withrights",
        "maintainer": "",
        "od_conformance": "approved",
        "osd_conformance": "not reviewed",
        "status": "retired",
        "title": "UK Crown Copyright with data.gov.uk rights",
        "url": ""
    },
    "ukpsi": {
        "domain_content": True,
        "domain_data": False,
        "domain_software": False,
        "family": "",
        "id": "ukpsi",
        "maintainer": "",
        "od_conformance": "rejected",
        "osd_conformance": "not reviewed",
        "status": "active",
        "title": "UK PSI Public Sector Information",
        "url": "https://opendefinition.org/licenses/ukpsi"
    }
}

lizenzen = {
    "daten": set(),
}

for lizenz in data:
    lizenzen["daten"].add(lizenz),
    lizenzen["daten"].add(data[lizenz]["title"])
    lizenzen["daten"].add(data[lizenz]["url"])

nicht_offen = (2, 5, 13, 26, 54)